### PR TITLE
First stab at new web site

### PR DESCRIPTION
**Pull request by matthew-mizielinski**
Addresses #14

In this pull request I have
 * Changed to the [pages-themes/minimal](https://github.com/pages-themes/minimal) theme (from `cayman`)
 * Added CMIP6 information including those suggested in  matthew-mizielinski/matthew-mizielinski.github.io#1
 * Added placemarker pages for ESGF, CMIP5, CMIP3
 * Minor alterations to the index page
 * Added layout information in `_layout/default.html` based on pages-themes/minimal
 * Added icon and logo pointers (taken from WGCM pages or pointer to them -- needs coarser resolution logo) to `_config.yml`
 * Added Gemfile (required by Ruby/Jekyll)
 * Added `environment.yml` to allow conda environment to be built.

There are also notes on configuring / running the Jekyll server on the [wiki](../wiki).

@durack1, I'd suggest focusing on structure here, i.e. can you get to a point where you can make changes using the instructions on the wiki and then we can break out a number of issues on content.

### CODE REVIEW

**Comment by matthew-mizielinski** [comment]
Yep. My plan was to get something functional and then we can all start tinkering with the content

**Comment by durack1** [comment]
@matthew-mizielinski looks like we've hit a build error on the github pages side, see [here](https://github.com/WCRP-CMIP/WGCM_Infrastructure_Panel/runs/3476561167), so the page isn't updated - just trying to figure out how to diagnose what the problem is, not sure [troubleshooting-build-errors](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/troubleshooting-jekyll-build-errors-for-github-pages-sites#troubleshooting-build-errors) will provide you much info. I'm not sure which issues may be the culprit

**Comment by durack1** [comment]
@matthew-mizielinski just to note, there is no major urgency here, we still have the old page live. So status quo from a visitor point of view

**Comment by durack1** [comment]
I'm wondering whether we have to prime the github pages env too - this makes me wonder https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll#updating-the-github-pages-gem

**Comment by durack1** [comment]
@matthew-mizielinski seems we hit a GitHub pages bug https://github.community/t/github-page-checks-not-populating/198809

**Comment by matthew-mizielinski** [comment]
@durack1 -- fixed by #17. I'll comment on the github pages bug in a second.

**Pull request merged**
